### ISSUE TITLE
vintage blip file makes the flash flicker 

### ISSUE THREAD

**Issue by charachk** [prokrypt/campsnap-fun#3]
Got my first camera just over a month ago, uploaded the blip vintage file following the instructions on their website and, upon updating the camera with the vintage blip file, the flash began flickering. Contacted camp snap support, they sent me out a brand new camera unit, updated it again with the vintage blip file, and again now the flash is not operating the correct way. Any fixes for this? Really really prefer the blip sound over the factory and silent settings.

**Comment by charachk** [comment]
Updating the camera to the vintage filter with factory sound makes flash go back to normal. Seems blip vintage file somehow makes the flash unit flicker

**Comment by prokrypt** [comment]
Interesting! Thanks for bringing this to my attention.

It seems there is a newer version of the firmware (1628.bin) in the zips available on the support site, probably for newer revision hardware as I don't have this problem on mine. I have grabbed and patched it. If you would like to see if it fixes your problem, I have attached it below.

I've only tested it on my camera to make sure it doesn't brick or explode (it did neither).
[blips-vtg-new.zip](https://github.com/user-attachments/files/16619224/blips-vtg-new.zip)

**Comment by charachk** [comment]
Hey, thank you so much for the response! Unfortunately, same issue persists even with the new files you attached :( and again, uploaded files straight from website, flash works again.

**Comment by charachk** [comment]
This is actually the second unit I am testing it on. I originally bought my first a few months ago and didnt make the connection that it was due to installing the blip zips until I reached out to customer support about the flash and they ever so kindly sent me a second replacement unit. Tested, flash fine out of box, upload blip zips, flash flickering. Thank you again for the support! Hope this is an easy fix!

**Comment by prokrypt** [comment]
Easy fix indeed. Looks like I actually patched an old binary instead of the new one in that last zip I uploaded. Too many files in my dev folder. Oops! :sweat:

The following should be the right one this time!
[blips-vtg-newest.zip](https://github.com/user-attachments/files/16621582/blips-vtg-newest.zip) (tested on my own camera--no bricks or explosions)

**Comment by charachk** [comment]
Awesome, works great! Thank you so much!! 👍 Appreciate it 😄

**Comment by prokrypt** [comment]
You have my thanks too! I finally started working on my patch script again so I don't have to patch each audio snippet manually. Maybe in the future I can make a tool for users to use their own audio snippets...
![patchy](https://github.com/user-attachments/assets/4be746e4-a448-48da-82bb-c5280356bcd0)
